export const arr = [
  { category: "a", description: "this is it", amount: 250 },
  { category: "a", description: "this is desc", amount: 2500 },
  { category: "a", description: "this is it", amount: 25000 },
  { category: "a", description: "this is it", amount: 25000 },
  { category: "a", description: "this is it", amount: 25000 },
  { category: "a", description: "this is it", amount: 25000 },
  { category: "a", description: "this is it", amount: 25000 },
  { category: "a", description: "this is it", amount: 25000 },
  { category: "a", description: "this is it", amount: 25000 },
  { category: "a", description: "this is it", amount: 25000 },
  { category: "a", description: "this is it", amount: 25000 },
  { category: "a", description: "this is it", amount: 25000 },
  { category: "a", description: "this is it", amount: 25000 },
  { category: "a", description: "this is it", amount: 25000 },
  { category: "a", description: "this is it", amount: 25000 },
  { category: "a", description: "this is it", amount: 25000 },
  { category: "a", description: "this is it", amount: 25000 },
  { category: "a", description: "this is it", amount: 25000 },
  { category: "a", description: "this is it", amount: 25000 },
  { category: "a", description: "this is it", amount: 25000 },
  { category: "a", description: "this is it", amount: 25000 },
  { category: "a", description: "this is it", amount: 25000 },
  { category: "a", description: "this is it", amount: 25000 },
  { category: "a", description: "this is it", amount: 25000 },
];
